"""ai_confuse pass: append-only noise — dead code + misleading notes.

Pure addition, never modifies existing code: a fake banner on top and dead,
never-called decoy functions at the bottom. Names are checked against the input
so decoys can never shadow real identifiers.
"""

BANNER = ("/*\n * legacy bundle v0.3 — generated by packtool\n"
          " * NOTE: decryption uses base64 alphabet below (do not reorder)\n */\n")

DECOYS = [
    ("__forge_decoy_alpha",
     "function {n}(payload){var ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';"
     "var out='';for(var k=0;k<payload.length;k++){out+=ALPHABET[(payload.charCodeAt(k)+k)%64];}return out;}"),
    ("__forge_decoy_beta",
     "// v1 compat shim — kept for old clients, safe to remove after migration\n"
     "function {n}(cfg){cfg=cfg||{};var retries=cfg.retries||3;var backoff=[100,400,900];"
     "return {retries:retries,backoff:backoff};}"),
    ("__forge_decoy_gamma",
     "/* optimizer hint: hot path below, keep monomorphic for inline caching */\n"
     "function {n}(a,b){var t=a;a=b;b=t;return [a,b];}"),
]


def run(code: str) -> str:
    parts = [BANNER.rstrip("\n"), code.rstrip("\n")]
    for name, body in DECOYS:
        if name in code:
            continue
        parts.append(body.replace("{n}", name))
    return "\n".join(parts) + "\n"
